### ISSUE TITLE
Error "double free or corruption (!prev)"

### ISSUE THREAD

**Issue by naikymen** [naikymen/cellID-linux#8]
double free or corruption (!prev)

Prints when using CellID mask_mod from Rcell2 on an image convolved by imagemagick:

    mogrify -bias 50% -morphology Convolve DoG:0,1.8,2.4 -define showkernel=1 -path convolutioned *.tif

When the image is cropped to approximately half (vertical cut), the error dissappears.

Used images attached: [cellid.zip](https://github.com/darksideoftheshmoo/cellID-linux/files/5636858/cellid.zip)

**Comment by naikymen** [comment]
New data for this bug: [bug_data.zip](https://github.com/darksideoftheshmoo/cellID-linux/files/7891911/bug_data.zip)

Using `gdb` to debug revealed the cause.

This was tested in the `mask_mod_make` branch, fixed by commit 758a9c613e16d96233be9aeedf3eca319687f3d0

See notes below.

**Comment by naikymen** [comment]
# Cause for "double free or corruption (!prev)"

CellID no procesa ciertas fotos. Cuando le toca a una de esas fotos pasa esto:

```
----------------------------------------------------
New Fluorescence image: /tmp/rcell.test.dir/dir649d396b4a60/TFP_Position11_time3.tif.
----------------------------------------------------
Not doing any flattening correction.
Doing new cell search.
New brightfield image: /tmp/rcell.test.dir/dir649d396b4a60/BF_Position11_time3.tif.
Doing linear-correction to flatten image.
mean and sig: 9.070790e+03,-nan
In Pixel units: mu=9.070790e+03, sig=-nan.
BF-cut-low=-nan, BF-cut-high=-nan
double free or corruption (!prev)
```

Una pista estaba en `sig=-nan`, parece que en el cálculo de un desvio estándar se generan `NaN`s.

`gdb` detectó el error en `segment.c`:

```gdb
double free or corruption (!prev)

Program received signal SIGABRT, Aborted.
0x00007ffff7a14d22 in raise () from /usr/lib/libc.so.6
(gdb) where
#0  0x00007ffff7a14d22 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff79fe862 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff7a56d28 in __libc_message () from /usr/lib/libc.so.6
#3  0x00007ffff7a5e92a in malloc_printerr () from /usr/lib/libc.so.6
#4  0x00007ffff7a601bc in _int_free () from /usr/lib/libc.so.6
#5  0x00007ffff7a639e8 in free () from /usr/lib/libc.so.6
#6  0x0000555555576e58 in do_contiguous_search (csearch=0x7ffffffe4ad0) at contiguous.c:257
#7  0x000055555555d4b6 in find_cells (boundary_out=0x7ffffffe55e8, interior_out=0x7ffffffe55f0) at segment.c:949
#8  0x000055555555afb4 in main (argc=9, argv=0x7fffffffdfe8) at cell.c:1640
```

Resulta que están usando la fórmula (E(X²) - E²(X))^(1/2) para el desvío estándar.

Wikipedia no lo recomienda, porque da lugar a [cancelaciones catastróficas](https://en.wikipedia.org/wiki/Catastrophic_cancellation).

Sin embargo, ese no era el problema. Los términos de la resta eran bastante diferentes.

De las cosas que probé, solo funcionó incrementar la precisión de las variables que iban guardando
las sumas para las cuentas de la media y del sigma. Abajo hay un ejemplo de la diferencia entre
usar la precisión original y la doble.

Usando normal "float" type (el original):

    mean and sig: 9.070790e+03,-nan

Usando double precision type (lo que elegí yo):

    mean, sig and scale (after scaling): 9.026486e+03, 8.208091e+07, 1.447680e+06
    variance and stdev: 6.034577e+05, 8.208091e+07

La media (en realidad la suma antes de dividir por N) es un poco más grande usando float.

Y eso genera una varianza negativa, que va dentro de la raíz cuadrada, y eso genera el "NaN" en el sigma final.

# Descripción del patch

Cambié en el function setup:

    float mu,sig,scale;

Por:

    double mu,sig,scale;

Y en el for loop cambié:

    mu+=tmp;
    sig+=(tmp*tmp);
    scale+=1.0;

Por:

    mu+=(double)(tmp);
    sig+=(double)(tmp*tmp);
    scale+=1.0;

Y con eso se arregló el problema.

> Estúpido programa abandonado -.-

**Comment by naikymen** [comment]
Acá dejo algo de info sobre debugging de C con gdb: https://wiki.frubox.org/proyectos/atc
